# Generated by Django 3.2.5 on 2023-03-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asuransi', models.CharField(max_length=500)),
                ('nama_provider', models.CharField(max_length=500)),
                ('alamat', models.CharField(max_length=500)),
                ('label_name', models.CharField(max_length=300)),
                ('proba_score', models.CharField(max_length=10)),
                ('count_label_name', models.CharField(max_length=2)),
                ('ri', models.CharField(max_length=2)),
                ('rj', models.CharField(max_length=2)),
            ],
        ),
    ]
