# Generated by Django 3.2.5 on 2023-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprovider',
            name='validity',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
