# Generated by Django 3.2.5 on 2023-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_goldenrecordmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprovider',
            name='golden_record',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
