# Generated by Django 3.2.5 on 2022-11-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_provider_perbandingan'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_perbandingan',
            name='nama_asuransi',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
    ]
