# Generated by Django 3.2.5 on 2023-04-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20230418_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenrecordmatch',
            name='status',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goldenrecordmatch',
            name='total_ratio',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
