# Generated by Django 3.2.5 on 2023-04-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_itemprovider_alamat_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprovider',
            name='id_model',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
