# Generated by Django 3.2.5 on 2023-04-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprovider',
            name='ratio',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemprovider',
            name='total_score',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
