# Generated by Django 3.2.5 on 2023-04-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20230411_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprovider',
            name='alamat_ratio',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
